import = ["/home/jay/.config/alacritty/catppuccin-mocha.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 12

[font.normal]
family = "IosevkaTerm Nerd Font"

[window]
dynamic_padding = true
opacity = 0.7
