import = ["/home/jay/.config/alacritty/catppuccin-mocha.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 11

[font.normal]
family = "GohuFont 11 Nerd Font Mono"

[window]
dynamic_padding = true
opacity = 0.3
